# Generated by Django 4.2 on 2023-05-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='publish_date',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
