# Generated by Django 4.2 on 2023-05-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_news_author_alter_news_publish_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default='E:\\Folder3\\server\\web\\static\\image\\carousel1.png', upload_to='news_images'),
        ),
    ]
